DROP TABLE IF EXISTS support_tickets;
DROP TABLE IF EXISTS products;
DROP TABLE IF EXISTS scans;
DROP TABLE IF EXISTS diseases;
DROP TABLE IF EXISTS refresh_tokens;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS roles;
